### ISSUE TITLE
Add CLI Options for Config File and Output Path

### ISSUE THREAD

**Issue by partisani** [Achno/gowall#24]
As the title says, this tool is too inflexible to be used correctly in most scenarios that involve scripts, especially ones embedded in places like a NixOS configuration.

Some things that should be changed:

* Theme and configuration should be allowed to load from files other than `~/.config/gowall/config.yml` via a command line argument
* The user should be allowed to change where the output file(s) is/are saved

*btw i still use this tool instead of other ones because this one is better*

**Comment by Achno** [comment]
Understandable, i will address these enhancements when the exam season is over because i'm overwhelmed right now i hope you understand.

**Comment by partisani** [comment]
> i will address these enhancements when the exam season is over because i'm overwhelmed right now, i hope you understand.

No pressure or anything, it is ok.

> Could you explain why config.yml path should be configured? What problems did you face with the standard config files in ~/.config ?

I found that generating the colorscheme from a script or something else would require the configuration file to be overwritten everytime the colorscheme changed, which lead me to do [this](https://github.com/partisani/nixfiles/blob/main/modules/apps.gowall.nix) as a workaround. And always pass `base16` as the theme everytime i called gowall.

In my case, doing this forces Home-Manager to create and (re)build a derivation only to regenerate `gowall/config.yml` everytime, while some other tool called [dipc](https://github.com/doprz/dipc) allows the colors to be passed at runtime via command line arguments. *(to the detriment of other features i would need)*

**Comment by Achno** [comment]
@partisani  Okay since i had some free time i implemented these enhancements locally, and i just want you to give me feedback

1. You can now specify the `OutputFolder` in `~/.config/gowall/config.yml` : The below sets the directory to `~/MyImages`

```yml
OutputFolder: "MyImages"
themes: ....
```

2. You can now load themes in runtime via giving  a `.json` file in combination with the usual `-t` flag for the theme

```bash
gowall convert ~/Pictures/img.png -t test.json
``` 
You can use a relative path with `~` with the json file like this  :
```bash
gowall convert ~/Pictures/img.png -t ~/clr/test.json
```

The `test.json` **must** have the following interface  : 

```json
{
    "name": "MyTheme",
    "colors": [
        "#F5E0DC",
        "#F2CDCD",
        "#F5C2E7",
        "#11111B"
    ]
}
``` 
What do you think ?

**Comment by partisani** [comment]
I think now the only thing missing is something like `-o <output file>`, but the rest already works very well!

**Comment by Achno** [comment]
@partisani 

> I think now the only thing missing is something like -o output file

Oh, that already exists, someone made an issue here : https://github.com/Achno/gowall/issues/22 and i already implemented the functionality. Must have forgot to put it in the docs. You must get the version from the main branch though.

Well, i will test the above enhancements for more bugs and push it to main when i have more time.  In 3 weeks once the exam season ends `v.0.2.0` will be released and shortly after with all the goodies, NixOS should be up to date in a day too ;)

**Comment by partisani** [comment]
Then that's it! Thanks!

**Comment by Achno** [comment]
Reopening to close it when i push the enhancements to main

**Comment by Achno** [comment]
Implemented in https://github.com/Achno/gowall/commit/992690ac3019f8654ca0a33a66b09f5a240bf9b5 closing

**Comment by prurigro** [comment]
I created `~/.config/gowall/config.yml` containing only `OutputFolder: "MyImages"`, but images are still getting saved to `~/Pictures/gowall/`. I confirmed that I'm using the latest sources. Any ideas?

**Comment by Achno** [comment]
Reopening for investigation.

@prurigro 
> I confirmed that I'm using the latest sources

What do you mean by `latest sources` ? Are you using a released version? Like the Void, Aur or nixOS ? Because this update is not there  i have not released a new version for some months now, The latest release is `v0.1.9`.

All the updates that i have been doing in the main branch will be released in `v.0.2.0` which will come in 2 weeks.

- Now if you mean that you have the latest commit of gowall's main branch give me more information
 
1)Linux  Distro or Operating system?
2) How did you download it? git clone? 
3) on what commit did you git cloned if you did, https://github.com/Achno/gowall/commit/992690ac3019f8654ca0a33a66b09f5a240bf9b5 ?

**Comment by prurigro** [comment]
You know what, you're right. I was under the impression that `@latest` got the latest sources from git and not the latest release, but it's clear that I was on 0.1.9 when I dig into the files that were downloaded. It seems like `@main` grabs what I was expecting.

Apologies for the noise. Very cool tool btw!

**Comment by partisani** [comment]
Given that there seems to be no problem, i will close the issue on behalf of @Achno

**Comment by Achno** [comment]
> Edit: on a side note, running gowall -v on both 0.1.9 and the latest main returns gowall version: v0.1.8

Yea... kinda forgot to update the flag on that one. my bad lol

**Comment by partisani** [comment]
> > Edit: on a side note, running gowall -v on both 0.1.9 and the latest main returns gowall version: v0.1.8
> 
> Yea... kinda forgot to update the flag on that one. my bad lol

Oh, so that is why i thought my NixOS setup was broken lol
